build:
  nodes:
    my-tests:
      environment:
        php:
          version: 5.6
          version: 7.0
          version: 7.1
          version: 7.2
          version: 7.3
          version: 7.4
          version: 8.0
          version: 8.1
